version: '2'
services:

  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - mysql
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./conf/certs:/etc/nginx/ssl
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
    volumes_from:
      - code
  php:
    build: .
    working_dir: /var/www
    volumes_from:
      - code

  mysql:
    image: mariadb:10.2
    ports:
      - "33061:3306"
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  code:
    image: busybox
    volumes:
      - ./www:/var/www
